# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce04d71ae3ee1469a2ed117c2d37f4601fa1f6c0722803828b71c2029e5a6723f9df017d3a7c1eea4ce8d371bf4f67d0e03ff99dd31e56702ddc486fc959e136

test:
  secret_key_base: 0dc496f2f0a5f96bcdfa87adf2cb6e6fc042c9823bb9447151c08fe2fdeaa98394591e455dee3a4217339df41d1322d1d1222a6070e87063982da4ac9b8d7b86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
